// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package session

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserSession struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSession) Reset()         { *m = UserSession{} }
func (m *UserSession) String() string { return proto.CompactTextString(m) }
func (*UserSession) ProtoMessage()    {}
func (*UserSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{0}
}

func (m *UserSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSession.Unmarshal(m, b)
}
func (m *UserSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSession.Marshal(b, m, deterministic)
}
func (m *UserSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSession.Merge(m, src)
}
func (m *UserSession) XXX_Size() int {
	return xxx_messageInfo_UserSession.Size(m)
}
func (m *UserSession) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSession.DiscardUnknown(m)
}

var xxx_messageInfo_UserSession proto.InternalMessageInfo

func (m *UserSession) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserSession) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SessionValue struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionValue) Reset()         { *m = SessionValue{} }
func (m *SessionValue) String() string { return proto.CompactTextString(m) }
func (*SessionValue) ProtoMessage()    {}
func (*SessionValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{1}
}

func (m *SessionValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionValue.Unmarshal(m, b)
}
func (m *SessionValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionValue.Marshal(b, m, deterministic)
}
func (m *SessionValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionValue.Merge(m, src)
}
func (m *SessionValue) XXX_Size() int {
	return xxx_messageInfo_SessionValue.Size(m)
}
func (m *SessionValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionValue.DiscardUnknown(m)
}

var xxx_messageInfo_SessionValue proto.InternalMessageInfo

func (m *SessionValue) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SessionKey struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionKey) Reset()         { *m = SessionKey{} }
func (m *SessionKey) String() string { return proto.CompactTextString(m) }
func (*SessionKey) ProtoMessage()    {}
func (*SessionKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{2}
}

func (m *SessionKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionKey.Unmarshal(m, b)
}
func (m *SessionKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionKey.Marshal(b, m, deterministic)
}
func (m *SessionKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionKey.Merge(m, src)
}
func (m *SessionKey) XXX_Size() int {
	return xxx_messageInfo_SessionKey.Size(m)
}
func (m *SessionKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionKey.DiscardUnknown(m)
}

var xxx_messageInfo_SessionKey proto.InternalMessageInfo

func (m *SessionKey) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Nothing struct {
	D                    bool     `protobuf:"varint,1,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6be1b361fa6f14, []int{3}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetD() bool {
	if m != nil {
		return m.D
	}
	return false
}

func init() {
	proto.RegisterType((*UserSession)(nil), "session.UserSession")
	proto.RegisterType((*SessionValue)(nil), "session.SessionValue")
	proto.RegisterType((*SessionKey)(nil), "session.SessionKey")
	proto.RegisterType((*Nothing)(nil), "session.Nothing")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_3a6be1b361fa6f14) }

var fileDescriptor_3a6be1b361fa6f14 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x8c, 0xb9,
	0xb8, 0x43, 0x8b, 0x53, 0x8b, 0x82, 0x21, 0x5c, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0x4c, 0x17, 0x21, 0x11, 0x2e, 0x56, 0xd7, 0xdc, 0xc4, 0xcc,
	0x1c, 0x09, 0x26, 0xb0, 0x10, 0x6b, 0x2a, 0x88, 0xa3, 0xa4, 0xc2, 0xc5, 0x03, 0xd5, 0x10, 0x96,
	0x98, 0x53, 0x9a, 0x8a, 0x50, 0xc5, 0x88, 0xac, 0x4a, 0x86, 0x8b, 0x0b, 0xaa, 0xca, 0x3b, 0xb5,
	0x12, 0xdd, 0x64, 0x25, 0x71, 0x2e, 0x76, 0xbf, 0xfc, 0x92, 0x8c, 0xcc, 0xbc, 0x74, 0x21, 0x1e,
	0x2e, 0xc6, 0x14, 0xb0, 0x0c, 0x47, 0x10, 0x63, 0x8a, 0xd1, 0x4a, 0x46, 0x2e, 0x6e, 0xc7, 0xd2,
	0x92, 0x0c, 0xe7, 0x8c, 0xd4, 0xe4, 0xec, 0xd4, 0x22, 0x21, 0x23, 0x2e, 0x36, 0xe7, 0xa2, 0xd4,
	0xc4, 0x92, 0x54, 0x21, 0x11, 0x3d, 0x98, 0x27, 0x90, 0x9c, 0x2c, 0x25, 0x00, 0x17, 0x85, 0x9a,
	0xa7, 0xc4, 0x20, 0x64, 0xcc, 0xc5, 0xec, 0x9e, 0x5a, 0x22, 0x24, 0x0c, 0x97, 0x42, 0x38, 0x44,
	0x4a, 0x14, 0x5d, 0x10, 0xec, 0x07, 0x25, 0x06, 0x21, 0x43, 0x2e, 0x36, 0x97, 0xd4, 0x9c, 0xd4,
	0x92, 0x54, 0xec, 0xfa, 0xb0, 0xd8, 0x93, 0xc4, 0x06, 0x0e, 0x4d, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x91, 0xbe, 0x79, 0x0c, 0x5e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthCheckerClient is the client API for AuthChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthCheckerClient interface {
	Create(ctx context.Context, in *UserSession, opts ...grpc.CallOption) (*Nothing, error)
	Get(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*SessionValue, error)
	Delete(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*Nothing, error)
}

type authCheckerClient struct {
	cc *grpc.ClientConn
}

func NewAuthCheckerClient(cc *grpc.ClientConn) AuthCheckerClient {
	return &authCheckerClient{cc}
}

func (c *authCheckerClient) Create(ctx context.Context, in *UserSession, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/session.AuthChecker/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCheckerClient) Get(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*SessionValue, error) {
	out := new(SessionValue)
	err := c.cc.Invoke(ctx, "/session.AuthChecker/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCheckerClient) Delete(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/session.AuthChecker/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCheckerServer is the server API for AuthChecker service.
type AuthCheckerServer interface {
	Create(context.Context, *UserSession) (*Nothing, error)
	Get(context.Context, *SessionKey) (*SessionValue, error)
	Delete(context.Context, *SessionKey) (*Nothing, error)
}

func RegisterAuthCheckerServer(s *grpc.Server, srv AuthCheckerServer) {
	s.RegisterService(&_AuthChecker_serviceDesc, srv)
}

func _AuthChecker_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSession)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCheckerServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.AuthChecker/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCheckerServer).Create(ctx, req.(*UserSession))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthChecker_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCheckerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.AuthChecker/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCheckerServer).Get(ctx, req.(*SessionKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthChecker_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCheckerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.AuthChecker/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCheckerServer).Delete(ctx, req.(*SessionKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthChecker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "session.AuthChecker",
	HandlerType: (*AuthCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AuthChecker_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AuthChecker_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AuthChecker_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
